---
- name: Install any necessary dependencies [Debian/Ubuntu]
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-httplib2
    - python-apt
    - curl

- name: Import InfluxData GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: kapacitor_install_url is not defined or kapacitor_install_url == None

- name: Add InfluxData repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ kapacitor_install_version }}
    state: present
  when: kapacitor_install_url is not defined or kapacitor_install_url == None

- name: Install Kapacitor packages [Debian/Ubuntu]
  apt:
    name: kapacitor
    state: latest
  when: kapacitor_install_url is not defined or kapacitor_install_url == None

- name: Download Kapacitor package via URL [Debian/Ubuntu]
  command: curl -o /tmp/kapacitor-ansible-download.deb {{ kapacitor_install_url }}
  when: kapacitor_install_url is defined and kapacitor_install_url != None

- name: Install downloaded Kapacitor package [Debian/Ubuntu]
  apt:
    deb: /tmp/kapacitor-ansible-download.deb
    state: present
  when: kapacitor_install_url is defined and kapacitor_install_url != None
