---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl

- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes
  when: kapacitor_install_url is not defined or kapacitor_install_url == None

- name: Install Kapacitor packages [RHEL/CentOS]
  yum:
    name: kapacitor
    state: present
  when: kapacitor_install_url is not defined or kapacitor_install_url == None

- name: Install Kapacitor from URL [RHEL/CentOS]
  yum:
    name: "{{ kapacitor_install_url }}"
    state: present
  when: kapacitor_install_url is defined and kapacitor_install_url != None
